
import { Product, PromoCode } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Pro Gamer Desktop X',
    nameAr: 'برو جيمر ديسكتوب X',
    category: 'pc',
    price: 1200,
    costPrice: 900,
    image: 'https://picsum.photos/seed/pc1/600/400',
    description: 'High performance gaming PC with RTX 4070.',
    descriptionAr: 'جهاز كمبيوتر ألعاب عالي الأداء مع RTX 4070.',
    stock: 5,
    specifications: [
      { label: 'CPU', value: 'Intel Core i9-13900K' },
      { label: 'GPU', value: 'NVIDIA RTX 4070 12GB' },
      { label: 'RAM', value: '32GB DDR5' },
      { label: 'Storage', value: '1TB NVMe SSD' }
    ]
  },
  {
    id: '2',
    name: 'ZenBook Ultrathin',
    nameAr: 'زين بوك الترا ثين',
    category: 'laptop',
    price: 950,
    costPrice: 750,
    image: 'https://picsum.photos/seed/laptop1/600/400',
    description: 'Lightweight and powerful laptop for professionals.',
    descriptionAr: 'لاب توب خفيف الوزن وقوي للمحترفين.',
    stock: 3,
    specifications: [
      { label: 'CPU', value: 'AMD Ryzen 7 7840U' },
      { label: 'RAM', value: '16GB LPDDR5' },
      { label: 'Display', value: '14" 2.8K OLED' }
    ]
  },
  {
    id: '3',
    name: 'Mechanical Keyboard RGB',
    nameAr: 'لوحة مفاتيح ميكانيكية RGB',
    category: 'accessories',
    price: 85,
    costPrice: 50,
    image: 'https://picsum.photos/seed/kb1/600/400',
    description: 'Ultra-responsive switches with custom lighting.',
    descriptionAr: 'مفاتيح فائقة الاستجابة مع إضاءة مخصصة.',
    stock: 20,
    specifications: [
      { label: 'Switches', value: 'Mechanical Brown' },
      { label: 'Backlight', value: 'RGB' }
    ]
  }
];

export const INITIAL_PROMOS: PromoCode[] = [
  { id: 'p1', code: 'WELCOME10', discountPercentage: 10, active: true, usageLimit: 100, usedCount: 15 },
  { id: 'p2', code: 'ELKAFRAWY', discountPercentage: 15, active: true, usageLimit: 50, usedCount: 5 }
];

export const TRANSLATIONS = {
  en: {
    storeName: 'Elkafrawy Modern Tech',
    admin: 'Admin',
    user: 'User',
    login: 'Login',
    logout: 'Logout',
    dashboard: 'Dashboard',
    products: 'Products',
    orders: 'Orders',
    promoCodes: 'Promo Codes',
    addPromo: 'Add Promo',
    addProducts: 'Add Product',
    addToCart: 'Add to Cart',
    cart: 'Cart',
    checkout: 'Checkout',
    name: 'Full Name',
    phone: 'Phone Number',
    address: 'Address',
    confirmOrder: 'Confirm Order',
    instaPayInfo: 'Please pay via InstaPay to: 01550025915',
    doneMessage: 'Done! The product will reach you soon.',
    refusedMessage: 'Sorry, your order was refused.',
    pending: 'Pending',
    accepted: 'Accepted',
    refused: 'Refused',
    category: 'Category',
    all: 'All',
    pcs: 'PCs',
    laptops: 'Laptops',
    accessories: 'PC Accessories',
    price: 'Price',
    status: 'Status',
    actions: 'Actions',
    accept: 'Accept',
    refuse: 'Refuse',
    home: 'Home',
    stock: 'Stock',
    outOfStock: 'Out of Stock',
    delete: 'Delete',
    uploadImage: 'Upload Image',
    amount: 'Amount',
    quantity: 'Quantity',
    subtotal: 'Subtotal',
    discount: 'Discount',
    total: 'Total',
    apply: 'Apply',
    promoPlaceholder: 'Promo Code',
    priceBefore: 'Before Discount',
    priceAfter: 'After Discount',
    emptyCart: 'Your cart is empty',
    itemsCount: 'items',
    specifications: 'Specifications',
    label: 'Label',
    value: 'Value',
    usageLimit: 'Usage Limit',
    used: 'Used',
    remaining: 'Remaining',
    limitReached: 'Limit Reached',
    viewDetails: 'View Details',
    back: 'Back to Shop',
    copy: 'Copy',
    copied: 'Copied!',
    support: 'Support',
    startSupport: 'Start Support Chat',
    supportIntro: 'Provide your order info to chat with a specialist.',
    orderId: 'Order ID',
    invalidOrder: 'Invalid Order ID or Phone Number',
    typeMessage: 'Type a message...',
    send: 'Send',
    resolved: 'Resolved',
    activeSessions: 'Active Chats',
    howToGetOrderId: 'How to find your Order ID?',
    orderIdInstruction: 'The Order ID is the 9-character code shown on the screen after your purchase is confirmed. If you lost it, please contact our support team.',
    history: 'Login History',
    device: 'Device',
    location: 'Location',
    time: 'Time',
    analytics: 'Analytics',
    totalRevenue: 'Total Revenue',
    totalOrders: 'Total Orders',
    avgOrderValue: 'Avg Order Value',
    salesOverTime: 'Sales Over Time',
    bestSellers: 'Best Sellers',
    orderStatus: 'Order Status',
    revenue: 'Revenue',
    costPrice: 'Cost Price',
    profit: 'Profit',
    profitRatio: 'Profit Ratio',
    edit: 'Edit',
    done: 'Done',
    printReceipt: 'Print Receipt',
    receipt: 'Receipt',
    warrantyNotice: 'Warranty: 6 Months from purchase date',
    customerName: 'Customer Name',
    customerPhone: 'Customer Phone',
    customerAddress: 'Customer Address',
    orderDate: 'Order Date',
    itemsList: 'Items',
    paymentMethod: 'Payment Method',
    instapay: 'InstaPay',
    cod: 'Payment upon receipt',
    clearAllData: 'Clear All Data',
    clearDataConfirm: 'Are you sure you want to delete ALL orders and analytics? This cannot be undone.',
    dataCleared: 'All data cleared successfully.',
    reserve: 'Reserve Now',
    reserved: 'Reserved',
    reservationSuccess: 'Reservation placed successfully! We will contact you when available.',
    reservation: 'Reservation'
  },
  ar: {
    storeName: 'الكفراوي للتكنولوجيا الحديثه',
    admin: 'المسؤول',
    user: 'مستخدم',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    products: 'المنتجات',
    orders: 'الطلبات',
    promoCodes: 'أكواد الخصم',
    addPromo: 'إضافة كود',
    addProducts: 'إضافة منتج',
    addToCart: 'إضافة للسلة',
    cart: 'السلة',
    checkout: 'إتمام الشراء',
    name: 'الاسم بالكامل',
    phone: 'رقم الهاتف',
    address: 'العنوان',
    confirmOrder: 'تأكيد الطلب',
    instaPayInfo: 'يرجى الدفع عبر إنستا باي إلى: 01550025915',
    doneMessage: 'تم! المنتج سيصل إليك قريبًا.',
    refusedMessage: 'عذرًا، تم رفض طلبك.',
    pending: 'قيد الانتظار',
    accepted: 'مقبول',
    refused: 'مرفوض',
    category: 'الفئة',
    all: 'الكل',
    pcs: 'أجهزة كمبيوتر',
    laptops: 'لاب توب',
    accessories: 'ملحقات الكمبيوتر',
    price: 'السعر',
    status: 'الحالة',
    actions: 'الإجراءات',
    accept: 'قبول',
    refuse: 'رفض',
    home: 'الرئيسية',
    stock: 'المخزون',
    outOfStock: 'نفد من المخزون',
    delete: 'حذف',
    uploadImage: 'رفع صورة',
    amount: 'الكمية',
    quantity: 'الكمية',
    subtotal: 'المجموع الفرعي',
    discount: 'الخصم',
    total: 'الإجمالي',
    apply: 'تطبيق',
    promoPlaceholder: 'كود الخصم',
    priceBefore: 'السعر قبل الخصم',
    priceAfter: 'السعر بعد الخصم',
    emptyCart: 'سلة التسوق فارغة',
    itemsCount: 'قطع',
    specifications: 'المواصفات',
    label: 'العنوان',
    value: 'القيمة',
    usageLimit: 'حد الاستخدام',
    used: 'مستخدم',
    remaining: 'متبقي',
    limitReached: 'انتهى الحد',
    viewDetails: 'عرض التفاصيل',
    back: 'العودة للمتجر',
    copy: 'نسخ',
    copied: 'تم النسخ!',
    support: 'الدعم الفني',
    startSupport: 'بدء دردشة الدعم',
    supportIntro: 'أدخل بيانات طلبك للتحدث مع متخصص.',
    orderId: 'رقم الطلب',
    invalidOrder: 'رقم الطلب أو الهاتف غير صحيح',
    typeMessage: 'اكتب رسالة...',
    send: 'إرسال',
    resolved: 'تم الحل',
    activeSessions: 'الدردشات النشطة',
    howToGetOrderId: 'كيف تجد رقم طلبك؟',
    orderIdInstruction: 'رقم الطلب هو الكود المكون من 9 رموز والذي ظهر لك على الشاشة فور تأكيد الشراء. إذا فقدت الكود، يرجى التواصل مع الدعم الفني.',
    history: 'سجل الدخول',
    device: 'الجهاز',
    location: 'الموقع',
    time: 'الوقت',
    analytics: 'التحليلات',
    totalRevenue: 'إجمالي الإيرادات',
    totalOrders: 'إجمالي الطلبات',
    avgOrderValue: 'متوسط قيمة الطلب',
    salesOverTime: 'المبيعات بمرور الوقت',
    bestSellers: 'الأكثر مبيعاً',
    orderStatus: 'حالة الطلبات',
    revenue: 'الإيرادات',
    costPrice: 'سعر التكلفة',
    profit: 'الربح',
    profitRatio: 'نسبة الربح',
    edit: 'تعديل',
    done: 'تم',
    printReceipt: 'طباعة الفاتورة',
    receipt: 'فاتورة',
    warrantyNotice: 'الضمان: 6 أشهر من تاريخ الشراء',
    customerName: 'اسم العميل',
    customerPhone: 'رقم الهاتف',
    customerAddress: 'العنوان',
    orderDate: 'تاريخ الطلب',
    itemsList: 'الأصناف',
    paymentMethod: 'طريقة الدفع',
    instapay: 'إنستا باي',
    cod: 'الدفع عند الاستلام',
    clearAllData: 'مسح جميع البيانات',
    clearDataConfirm: 'هل أنت متأكد أنك تريد حذف جميع الطلبات والتحليلات؟ لا يمكن التراجع عن هذا الإجراء.',
    dataCleared: 'تم مسح جميع البيانات بنجاح.',
    reserve: 'احجز الآن',
    reserved: 'محجوز',
    reservationSuccess: 'تم الحجز بنجاح! سنتواصل معك عند التوفر.',
    reservation: 'حجز'
  }
};
